name = "OneClient 1.21.1 Fabric [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Utility"
id = "utility-1.21.1-fabric"
update-url = "oneclient/generated/utility-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "64fe91b97cb7c8b6c0d67167df61b51d4a1673ed00685a2b7c37ce73e868d841"

[versions]
fabric = "0.18.5"
minecraft = "1.21.1"
