name = "OneClient 1.21.1 Fabric [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Utility"
id = "utility-1.21.1-fabric"
update-url = "oneclient/generated/utility-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d570d20f6f92c6b2f0209eece64de0a3f51a335aa4578560983b7fb5bb8e2be9"

[versions]
fabric = "0.18.5"
minecraft = "1.21.1"
