name = "OneClient 1.21.1 Fabric [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Utility"
id = "utility-1.21.1-fabric"
update-url = "oneclient/generated/utility-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e39582625660a02ca45c7c988f1c5e7cd05a37988f4f14077c83685d2c168209"

[versions]
fabric = "0.18.5"
minecraft = "1.21.1"
