name = "OneClient 1.21.1 Fabric [Performance]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Performance"
id = "performance-1.21.1-fabric"
update-url = "oneclient/generated/performance-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c403b21b548da455a3c6ed537579f1c4b74dbb032bcc4f0e258901324bacc309"

[versions]
fabric = "0.18.5"
minecraft = "1.21.1"
