name = "OneClient 1.21.1 Fabric [Performance]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Performance"
id = "performance-1.21.1-fabric"
update-url = "oneclient/generated/performance-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4c8c374282ed7585e096fe65a9f78b98ebe930b3585c5729fc6edf6910c2baa6"

[versions]
fabric = "0.18.5"
minecraft = "1.21.1"
