name = "OneClient 1.21.1 Fabric [Performance]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Performance"
id = "performance-1.21.1-fabric"
update-url = "oneclient/generated/performance-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "da2c20c33df8e8866865cb1095bef318941240dac91175bef7e9577a698fbbb5"

[versions]
fabric = "0.18.5"
minecraft = "1.21.1"
