name = "OneClient 1.21.11 Fabric [SkyBlock]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "SkyBlock"
id = "skyblock-1.21.11-fabric"
update-url = "oneclient/generated/skyblock-1.21.11-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "075a0770225ac5fc44b69864e934af1fcf00c4816cace7176fe673f2180d0901"

[versions]
fabric = "0.18.5"
minecraft = "1.21.11"
