name = "OneClient 26.1 Fabric [Performance]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Performance"
id = "performance-26.1-fabric"
update-url = "oneclient/generated/performance-26.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7df5b0048a364263f92c38c607f54683c97a1b75f8007b112c9d3b62b10821e1"

[versions]
fabric = "0.18.5"
minecraft = "26.1"

[options]
acceptable-game-versions = []
