name = "OneClient 26.1 Fabric [Performance]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Performance"
id = "performance-26.1-fabric"
update-url = "oneclient/generated/performance-26.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e2019fc329145131e2de1687cc314a3f73d4c1c545ed317a53db3a04a5ce7b6"

[versions]
fabric = "0.18.5"
minecraft = "26.1"

[options]
acceptable-game-versions = []
