name = "OneClient 1.21.11 Fabric [Performance]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Performance"
id = "performance-1.21.11-fabric"
update-url = "oneclient/generated/performance-1.21.11-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a368292dca0d52eb217a0d50cde4b95d19a8fa920d1aec045291c75e15cfa06"

[versions]
fabric = "0.18.5"
minecraft = "1.21.11"

[options]
acceptable-game-versions = []
