name = "OneClient 1.21.11 Fabric [Performance]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Performance"
id = "performance-1.21.11-fabric"
update-url = "oneclient/generated/performance-1.21.11-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bba0302d2fa8295eff25b8095e5daaba71ab89d019c29e33c9e1869f0191b1d2"

[versions]
fabric = "0.18.5"
minecraft = "1.21.11"

[options]
acceptable-game-versions = []
