name = "OneClient 26.1 Fabric [PvP]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "PvP"
id = "pvp-26.1-fabric"
update-url = "oneclient/generated/pvp-26.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d098bdede6cc81f411f617d31edaa13918c16ae25d22ce790f6ab1e73378364"

[versions]
fabric = "0.18.5"
minecraft = "26.1"
