name = "OneClient 26.1 Fabric [PvP]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "PvP"
id = "pvp-26.1-fabric"
update-url = "oneclient/generated/pvp-26.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "46535e6d6631b3303163d1f48ab2d56f364e908feecab51b799fb53bff083f1b"

[versions]
fabric = "0.18.5"
minecraft = "26.1"
