name = "OneClient 26.1 Fabric [PvP]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "PvP"
id = "pvp-26.1-fabric"
update-url = "oneclient/generated/pvp-26.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df3eba51a31494a0292f36bb4eead8dc0fc207c1046b43998f5f35cf3da2d36c"

[versions]
fabric = "0.18.5"
minecraft = "26.1"
