name = "OneClient 1.21.10 Fabric [SkyBlock]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "SkyBlock"
id = "skyblock-1.21.10-fabric"
update-url = "oneclient/generated/skyblock-1.21.10-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f61054a435a556f0ea4bdc0e44c668fbc066a5501905b11ad7847ec1f61fc8e7"

[versions]
fabric = "0.18.5"
minecraft = "1.21.10"
