name = "OneClient 1.21.10 Fabric [SkyBlock]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "SkyBlock"
id = "skyblock-1.21.10-fabric"
update-url = "oneclient/generated/skyblock-1.21.10-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca0b6d93cd3b1b49d3759ae501e76a3e7e274881d8f3dd62931d37c05df68111"

[versions]
fabric = "0.18.5"
minecraft = "1.21.10"
