name = "OneClient 1.21.10 Fabric [Performance]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Performance"
id = "performance-1.21.10-fabric"
update-url = "oneclient/generated/performance-1.21.10-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ba2050c8c78d4ae745a4484274c3441ada75a95d19fe9b0fcb3db968790cd9e"

[versions]
fabric = "0.18.5"
minecraft = "1.21.10"
