name = "OneClient 1.21.10 Fabric [Performance]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Performance"
id = "performance-1.21.10-fabric"
update-url = "oneclient/generated/performance-1.21.10-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a7a950f5ea0a7e55b24dbef87ef9564304974f14fbd143d83e1228524bbf8ffe"

[versions]
fabric = "0.18.5"
minecraft = "1.21.10"
