name = "OneClient 1.21.10 Fabric [Performance]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Performance"
id = "performance-1.21.10-fabric"
update-url = "oneclient/generated/performance-1.21.10-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bfbf36d5bbf5f3b6b729d4b77a1640ca70191222b6469e821f2f1275ea096125"

[versions]
fabric = "0.18.5"
minecraft = "1.21.10"
