name = "OneClient 1.21.11 Fabric [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Utility"
id = "utility-1.21.11-fabric"
update-url = "oneclient/generated/utility-1.21.11-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1027b5395244317f44b9ed838abe80a089fb1bdddb50d4d8d3ba814f44fffbd3"

[versions]
fabric = "0.18.5"
minecraft = "1.21.11"
