name = "OneClient 1.21.11 Fabric [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Utility"
id = "utility-1.21.11-fabric"
update-url = "oneclient/generated/utility-1.21.11-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e4604d07535f9894bd31f8fdb6ab963c6a4a58431582335925e57ded21d38ce"

[versions]
fabric = "0.18.5"
minecraft = "1.21.11"
