name = "OneClient 1.21.11 Fabric [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Utility"
id = "utility-1.21.11-fabric"
update-url = "oneclient/generated/utility-1.21.11-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2faf54729cea68bedf370af432f984c8b4f86c0506e0bbb53113f552dba23ba3"

[versions]
fabric = "0.18.5"
minecraft = "1.21.11"
