name = "OneClient 1.21.11 Fabric [PvP]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "PvP"
id = "pvp-1.21.11-fabric"
update-url = "oneclient/generated/pvp-1.21.11-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9181ee7ee9bb5b96319baab7d8621ee0b085c10f7e82544baa687ba05c4b2779"

[versions]
fabric = "0.18.5"
minecraft = "1.21.11"
