name = "OneClient 1.21.11 Fabric [PvP]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "PvP"
id = "pvp-1.21.11-fabric"
update-url = "oneclient/generated/pvp-1.21.11-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d95c03ace6ae8b0ef6b9feed2ef4548ed150466fa9051d35c9fd9dd9ea86a167"

[versions]
fabric = "0.18.5"
minecraft = "1.21.11"
