name = "OneClient 1.21.11 Fabric [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "QoL"
id = "qol-1.21.11-fabric"
update-url = "oneclient/generated/qol-1.21.11-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "94d52723c8c85f86560c8befe84eb8df5b28482df5509d3d3013668e5a31dcca"

[versions]
fabric = "0.18.5"
minecraft = "1.21.11"

[options]
acceptable-game-versions = []
