name = "OneClient 1.21.11 Fabric [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "QoL"
id = "qol-1.21.11-fabric"
update-url = "oneclient/generated/qol-1.21.11-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "291225c759a1087777b0d86a3973d92c2db40fb5b1a7b0358f66dfadc6dbc8e1"

[versions]
fabric = "0.18.5"
minecraft = "1.21.11"

[options]
acceptable-game-versions = []
