name = "OneClient 26.1 Fabric [HUD]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "HUD"
id = "hud-26.1-fabric"
update-url = "oneclient/generated/hud-26.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e55df6742f6ab8ce6e00a04f54e930257c32c04a13409b277d9cfe7b34cd824f"

[versions]
fabric = "0.18.5"
minecraft = "26.1"
