name = "OneClient 26.1 Fabric [HUD]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "HUD"
id = "hud-26.1-fabric"
update-url = "oneclient/generated/hud-26.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d297bc7d8c2d88bf2d0d89befa26a1ac02cd84b4b801b197a88840884d771f2c"

[versions]
fabric = "0.18.5"
minecraft = "26.1"
