name = "OneClient 26.1 Fabric [HUD]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "HUD"
id = "hud-26.1-fabric"
update-url = "oneclient/generated/hud-26.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d32b3a8d27ff140a7dcc417cb79071620afea1729ce980c00ec5e4bd1191cb2"

[versions]
fabric = "0.18.5"
minecraft = "26.1"
