name = "OneClient 1.21.11 Fabric [HUD]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "HUD"
id = "hud-1.21.11-fabric"
update-url = "oneclient/generated/hud-1.21.11-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7fde1788fb4a8e6b287be3f8ab78349e7c985cc4a5f583136ccf056606d33f18"

[versions]
fabric = "0.18.5"
minecraft = "1.21.11"
