name = "OneClient 26.1 Fabric [SkyBlock]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "SkyBlock"
id = "skyblock-26.1-fabric"
update-url = "oneclient/generated/skyblock-26.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "65d16b203576dd76ddc80b1ba8c86a38c9770dc780ed289d11b0f63f7a43c6df"

[versions]
fabric = "0.18.5"
minecraft = "26.1"
