name = "OneClient 26.1 Fabric [SkyBlock]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "SkyBlock"
id = "skyblock-26.1-fabric"
update-url = "oneclient/generated/skyblock-26.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3afbae0ef34394b649097208b70b557f9a313c7016ff27b393a9901391c78831"

[versions]
fabric = "0.18.5"
minecraft = "26.1"
