name = "OneClient 26.1 Fabric [SkyBlock]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "SkyBlock"
id = "skyblock-26.1-fabric"
update-url = "oneclient/generated/skyblock-26.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a8848857b8b363582ad7fc8df86ea021ac4d35d1415dd78a67333e3e8ed27d17"

[versions]
fabric = "0.18.5"
minecraft = "26.1"
