name = "OneClient 26.1 Fabric [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "QoL"
id = "qol-26.1-fabric"
update-url = "oneclient/generated/qol-26.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "38fa0feb4ff11eaed26729106ca953d3ee528da59aa47f6e10d61fe4aeec3094"

[versions]
fabric = "0.18.5"
minecraft = "26.1"

[options]
acceptable-game-versions = []
