name = "OneClient 26.1 Fabric [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "QoL"
id = "qol-26.1-fabric"
update-url = "oneclient/generated/qol-26.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "518a90db47c677e7c27780471599513f82d1b5510ea7e393b55c533aea454fd3"

[versions]
fabric = "0.18.5"
minecraft = "26.1"

[options]
acceptable-game-versions = []
