name = "OneClient 26.1 Fabric [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "QoL"
id = "qol-26.1-fabric"
update-url = "oneclient/generated/qol-26.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7442e99ca01846aed688c7439082e811e8ba1a81d90d2aa9908a9113d74aa3fd"

[versions]
fabric = "0.18.5"
minecraft = "26.1"

[options]
acceptable-game-versions = []
