name = "OneClient 1.21.1 Fabric [PvP]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "PvP"
id = "pvp-1.21.1-fabric"
update-url = "oneclient/generated/pvp-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff3ed9541c27de17654588926d9e883300d28f48ae73a7c9913e036e3b4f5175"

[versions]
fabric = "0.18.5"
minecraft = "1.21.1"
