name = "OneClient 1.21.1 Fabric [PvP]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "PvP"
id = "pvp-1.21.1-fabric"
update-url = "oneclient/generated/pvp-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "425b11bb88341f137b822dcfe9568928e2ebe17d06bb9777630f604a9470d46d"

[versions]
fabric = "0.18.5"
minecraft = "1.21.1"
