name = "OneClient 1.21.10 Fabric [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "QoL"
id = "qol-1.21.10-fabric"
update-url = "oneclient/generated/qol-1.21.10-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cfd4f628070b4d79270fa572331c733f1c8530762ea46094b1b5b2f574309d00"

[versions]
fabric = "0.18.5"
minecraft = "1.21.10"
