name = "OneClient 1.21.10 Fabric [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "QoL"
id = "qol-1.21.10-fabric"
update-url = "oneclient/generated/qol-1.21.10-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c0610c5489d916fc2d9917b65516b90e0590679e3c0c1c95303767ff1572a64f"

[versions]
fabric = "0.18.5"
minecraft = "1.21.10"
