name = "OneClient 1.21.10 Fabric [HUD]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "HUD"
id = "hud-1.21.10-fabric"
update-url = "oneclient/generated/hud-1.21.10-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "071f203c444a8fc8050a1d58d799b565eda9a602ba7e32e46cf9129a139678ff"

[versions]
fabric = "0.18.5"
minecraft = "1.21.10"
