name = "OneClient 26.1 Fabric [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Utility"
id = "utility-26.1-fabric"
update-url = "oneclient/generated/utility-26.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7173e38e4b032180defda561147586d0ec5ebb5aaf21deea7572dabae108a481"

[versions]
fabric = "0.18.5"
minecraft = "26.1"
