name = "OneClient 26.1 Fabric [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Utility"
id = "utility-26.1-fabric"
update-url = "oneclient/generated/utility-26.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95066a0e826e89a34533e96eef26894e39af30eccd6a66e3a4f5ad26b4b575f6"

[versions]
fabric = "0.18.5"
minecraft = "26.1"
