name = "OneClient 26.1 Fabric [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Utility"
id = "utility-26.1-fabric"
update-url = "oneclient/generated/utility-26.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61918ee8dd0dd89baf772fe1f8230c580a07cc6dc3543f4fb7b99821a31d4569"

[versions]
fabric = "0.18.5"
minecraft = "26.1"
