name = "OneClient 1.21.1 Fabric [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "QoL"
id = "qol-1.21.1-fabric"
update-url = "oneclient/generated/qol-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20ad84b0764c0df50f46516d6b54c64fd3739f7a176f126efb4e5d45dd34c713"

[versions]
fabric = "0.18.5"
minecraft = "1.21.1"
