name = "OneClient 1.21.1 Fabric [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "QoL"
id = "qol-1.21.1-fabric"
update-url = "oneclient/generated/qol-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "79511eed7fc74c80c0c965baa49fa98e0c0fd73c5cf06538b1dcbd4dd00959f2"

[versions]
fabric = "0.18.5"
minecraft = "1.21.1"
