name = "OneClient 1.21.10 Fabric [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Utility"
id = "utility-1.21.10-fabric"
update-url = "oneclient/generated/utility-1.21.10-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a911fe3c288e72f8ad4e0b9c35e682e8a3ea9cb1514c988fa93cba88428b2bf"

[versions]
fabric = "0.18.5"
minecraft = "1.21.10"
