name = "OneClient 1.21.10 Fabric [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Utility"
id = "utility-1.21.10-fabric"
update-url = "oneclient/generated/utility-1.21.10-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc1fed73ff208d6ae3a5d8427bda66abd99bd6d12bcbc1dad300ad6354e59fc5"

[versions]
fabric = "0.18.5"
minecraft = "1.21.10"
