name = "OneClient 1.21.10 Fabric [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Utility"
id = "utility-1.21.10-fabric"
update-url = "oneclient/generated/utility-1.21.10-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7db43b4d5c3e493c7ed2b6928fdd777d8f7760af270551aae86636f8525a0568"

[versions]
fabric = "0.18.5"
minecraft = "1.21.10"
